paypewe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story1/', include('story1.urls')),
    path('', include('story3.urls')),
    path('schedule/', include('story4.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

handler404 = 'story3.views.error_404'

story1/urls.py
from django.contrib import admin
from django.urls import path, include
from story1 import views

app_name = "story1"

urlpatterns = [
    path('', views.index, name='idindex'),
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include
from story6 import views

app_name = "story6"

urlpatterns = [
   	path('', views.blank, name='idblank'),
   	path('kegiatan/', views.kegiatan, name='idkegiatan'),
   	path('kegiatanform/', views.kegiatanform, name='idkegiatanform'),
   	path('personform/<int:id>/', views.personform, name='idpersonform'),
]

story6/models.py
from django.db import models

# Create your models here.
class Activity(models.Model):
	id = models.AutoField(primary_key=True)
	nama = models.CharField(max_length=30, blank=False)

	class Meta:
		ordering = ['nama']

	def __str__(self):
		return self.nama

class Person(models.Model):
	nama = models.CharField(max_length=30, blank=False)
	activity = models.ForeignKey(Activity, on_delete=models.CASCADE)
	
	class Meta:
		ordering = ['nama']

	def __str__(self):
		return self.nama

story6/forms.py
from django import forms
from .models import Activity, Person


class ActivityForm(forms.ModelForm):
	class Meta:
		model = Activity
		fields = '__all__'
		exclude=['id']

	nama = forms.CharField(label='Nama Kegiatan', required=True, max_length=32, 
		widget = forms.TextInput(attrs={'class':'form-control','type' : 'text', 'placeholder' : 'Misal: Berenang, Piknik, dll'} ))
	
class PersonForm(forms.ModelForm):
	class Meta:
		model = Person
		fields = '__all__'
		exclude=['id', 'activity']

	nama = forms.CharField(label='Nama Peserta', required=True, max_length=32,  
		widget = forms.TextInput(attrs={'class':'form-control','type' : 'text', 'placeholder' : 'Misal: alfonso de albuquerque'} ))

story6/views.py
from django.shortcuts import render, redirect
from .models import Activity, Person
from .forms import ActivityForm, PersonForm

# Create your views here.
def blank(request):
	return redirect("story6:idkegiatan")

def kegiatan(request):
	activities = Activity.objects.all()
	persons = Person.objects.all()
	response = {'activities' : activities, 'persons' : persons}
	return render(request, 'kegiatan.html', response)

def kegiatanform(request):
	if (request.method == "POST"):
		form = ActivityForm(request.POST)
		if (form.is_valid):
			form.save()
			return redirect("story6:idkegiatan")

	form = ActivityForm()
	response = {'form' : form }
	return render(request, 'kegiatanform.html', response)

def personform(request, id):
	activity = Activity.objects.get(id=id)
	if (request.method == "POST"):
		form = PersonForm(request.POST)
		if (form.is_valid()):
			data = form.cleaned_data
			activity.person_set.create(nama=data['nama'])
			return redirect("story6:idkegiatan")

	form = PersonForm()
	response = {'form' : form, 'activity' : activity}
	return render(request, 'personform.html', response)

story6/templates/kegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'story6.css' %}">
<title>kegiatan</title>
</head>

<body id="kegiatan">
{% include 'navbar.html' %}
<div class = "container pagelist">

    <h1>KEGIATAN</h1>
    <div class="row justify-content-center"><hr class="line-b"></div>
    <br>

    <div class="row justify-content-center">
        {% for item in activities %}  
        <div class="card text-white bg-danger m-3" style="width: 20rem;">
            <div class="card-header text-center"><h4>{{ item }}</h4></div>
            <ul class="list-group list-group-flush">
                {% for person in item.person_set.all %}  
                    <li class="list-group-item bg-danger">{{ person }}</li>
                {% empty %}
                    <li class="list-group-item bg-danger">-</li>
                {% endfor %}  
            </ul>
            <br><a href="{% url 'story6:idpersonform' item.id %}">
            <button type="button" class="btn bg-warning joinbtn btn-md m-3">Daftar !</button></a>
        </div>
        {% empty %}
        <h1 style="color:red;">Kegiatan tidak ditemukan !</h1>
        {% endfor %}  
    </div>

    <br><br>
    <a href="{% url 'story6:idkegiatanform' %}">
    <button type="button" class="btn btn-primary btn-lg btn-block">Tambahkan Kegiatan Baru</button>
    </a>
</div>

{% endblock content %}

story6/templates/kegiatanform.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'story6.css' %}">
<title>Form Kegiatan</title>
</head>

<body id="kegiatan">
{% include 'navbar.html' %}

<div class = "container pageadd">
    <!-- back button -->
    <a href="{% url 'story6:idkegiatan' %}">
    <button type="button" class="btn btn-primary btn-md">Kembali</button>
    <br><br>
    </a>
	<h2>FORM PENAMBAHAN KEGIATAN BARU</h2>
	<br>
	<form action="{% url 'story6:idkegiatanform' %}" method="POST">
    	{% csrf_token %}
        {{form}}
    	<br>
        <button type="submit" class="btn btn-primary btn-lg btn-block">Submit Form</button>
	</form>
</div>


{% endblock content %}

story6/templates/personform.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'story6.css' %}">
<title>Form daftar {{ activity.nama }}</title>
</head>

<body id="kegiatan">
{% include 'navbar.html' %}

<div class = "container pageadd">
    <!-- back button -->
    <a href="{% url 'story6:idkegiatan' %}">
    <button type="button" class="btn btn-primary btn-md">Kembali</button>
    <br><br>
    </a>
	<h2>Form Pendaftaran Kegiatan</h2>
    <h2>{{ activity.nama }}</h2>
	<br>
	<form action="{% url 'story6:idpersonform' activity.id %}" method="POST">
    	{% csrf_token %}
        {{ form }}
    	<br>
        <button type="submit" class="btn btn-primary btn-lg btn-block">Submit Form</button>
	</form>
</div>


{% endblock content %}