paypewe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story1/', include('story1.urls')),
    path('', include('story3.urls')),
    path('schedule/', include('story4.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

handler404 = 'story3.views.error_404'

story1/urls.py
from django.contrib import admin
from django.urls import path, include
from story1 import views

app_name = "story1"

urlpatterns = [
    path('', views.index, name='idindex'),
]

story3/urls.py
from django.contrib import admin
from django.urls import path, include
from story3 import views

app_name = "story3"

urlpatterns = [
#id harus beda, id itu name="id"
    path('', views.intro, name='intro'),
    path('portofolio/', views.portofolio, name='portofolio'),
    path('404/<str:exception>/', views.error_404, name='404'),
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include
from story4 import views

app_name = "story4"

urlpatterns = [
   	path('', views.schedule, name='schedule'),
    path('isiform/', views.isiform, name='idisiform'),    
    path('detail-matkul/<int:id>', views.detail, name='iddetail'),
    path('detail-matkul/hapus/<int:id>', views.hapus, name='idhapus'),
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include
from story6 import views

app_name = "story6"

urlpatterns = [
   	path('', views.blank, name='idblank'),
   	path('kegiatan/', views.kegiatan, name='idkegiatan'),
   	path('kegiatanform/', views.kegiatanform, name='idkegiatanform'),
   	path('personform/<int:id>/', views.personform, name='idpersonform'),
]

story7/urls.py
from django.contrib import admin
from django.urls import path, include
from story7 import views

app_name = "story7"

urlpatterns = [
    path('', views.index, name='idindex'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Catamaran:wght@300&family=Varela&family=Sansita+Swashed&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Catamaran:wght@300&family=Itim&&display=swap" rel="stylesheet">
    <link rel = "icon" href ="{% static 'image/myicon.png' %}" type = "image/png"> 
    <!-- navbar css -->
    <style type="text/css">
    	.nav-img{
    		width:50px;
    		filter: drop-shadow(1px 1px 3px rgba(0, 0, 0, 0.2));
    	}
    	.nav-btn{
    		background-color: rgba(255, 255, 255, .15);  
 			backdrop-filter: blur(10px);
 			border-color: white;box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3);
    	}
    	.active{
		  background-color: #666;
		  color: blue;
		}
		.nav-link {
		    font-size: 20px;
		    text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.1);
		    font-family: 'Varela', sans-serif;
		}

		.nav-link:hover {
		    text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3);
		    font-family: 'Varela', sans-serif;
		}
        .txt-shdw {
            text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3);
        }
    </style>
{% block content %}

{% endblock content %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</body>
</html>


    

templates/navbar.html
{% load static%}
<!-- My Code -->
<nav class="navbar navbar-expand-md justify-content-center m-auto" id="1"> 
    <a class="nav-link" href="{% url 'story3:intro' %}">
        <img src="{% static 'image/myicon.png' %}" alt="logonavbar" type = "image/png" class="nav-img mx-2">
    </a>
    <div class="row align-middle">
        <a class="nav-link text-white" href="{% url 'story3:intro' %}">Intro</a>
        <a class="nav-link text-white" href="{% url 'story3:portofolio' %}">Portofolio</a>
        <a class="nav-link text-white" href="{% url 'story4:schedule' %}">Mata Kuliah</a>
        <a class="nav-link text-white" href="{% url 'story6:idkegiatan' %}">Kegiatan</a>
        <a class="nav-link text-white" href="{% url 'story7:idindex' %}"><i>Accordion</i></a>
        <a class="nav-link text-white" href="{% url 'story8:idindex' %}">Bookshelf</a>
        <a class="nav-link text-white" href="{% url 'story1:idindex' %}">Story 1</a>
    </div>
    <div style="margin-inline-start:auto;">
        {% if user.is_authenticated %}
            <div class="row align-middle align-items-center">
                <h4 class="txt-shdw text-white align-self-center">Welcome, {{ request.user.username}}</h4>
            	<a class="nav-link" href="{% url 'story9:profile' user.username %}">
                    <button type="button" class="btn btn-lg text-white nav-btn" style="">Profile</button>
                </a>
            </div>
        {% else %}
        	<a class="nav-link text-white" href="{% url 'story9:loginsite' %}"><button type="button" class="btn btn-lg text-white" style=" background-color: rgba(255, 255, 255, .15);  
     backdrop-filter: blur(10px);border-color: white;box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3);">Login</button></a>
        {% endif %}
    </div>
</nav>