paypewe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story1/', include('story1.urls')),
    path('', include('story3.urls')),
    path('schedule/', include('story4.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

handler404 = 'story3.views.error_404'

story1/urls.py
from django.contrib import admin
from django.urls import path, include
from story1 import views

app_name = "story1"

urlpatterns = [
    path('', views.index, name='idindex'),
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include
from story4 import views

app_name = "story4"

urlpatterns = [
   	path('', views.schedule, name='schedule'),
    path('isiform/', views.isiform, name='idisiform'),    
    path('detail-matkul/<int:id>', views.detail, name='iddetail'),
    path('detail-matkul/hapus/<int:id>', views.hapus, name='idhapus'),
]

story4/models.py
from django.db import models

# Create your models here.
class Matkul(models.Model):
	
	id = models.AutoField(primary_key=True)
	nama_matkul = models.CharField(max_length=32, blank=False)
	deskripsi = models.TextField(max_length=500, blank=True)
	dosen_pengajar = models.CharField(max_length=32, blank=False)
	ruang_kelas = models.CharField(max_length=32, blank=False)
	sks = models.PositiveSmallIntegerField(default=0)
	kapasitas = models.PositiveSmallIntegerField(default=0)
	semester = models.CharField(max_length=32)

	def __str__(self):
		return self.nama_matkul

story4/forms.py
from django import forms
from .models import Matkul

semester_choices = [
		('Gasal 2018/2019', 'Gasal 2018/2019'),
		('Genap 2018/2019', 'Genap 2018/2019'),
		('Gasal 2019/2020', 'Gasal 2019/2020'),
		('Genap 2019/2020', 'Genap 2019/2020'),
		('Gasal 2020/2021', 'Gasal 2020/2021'),
		('Genap 2020/2021', 'Genap 2020/2021'),
	]

class MatkulForm(forms.ModelForm):
	class Meta:
		model = Matkul
		fields = '__all__'
		exclude=['id']

	nama_matkul = forms.CharField(label='Nama Mata Kuliah', required=True, max_length=32, 
		widget = forms.TextInput(attrs={'class':'form-control','type' : 'text', 'placeholder' : 'Nama Mata Kuliah'} ))
	deskripsi = forms.CharField(label='Deskripsi', required=False, max_length=500,
		widget = forms.Textarea(attrs={'class':'form-control','type' : 'text', 'placeholder' : 'Deskripsi Mata Kuliah'} ))
	dosen_pengajar = forms.CharField(label="Dosen Pengajar", required=True, max_length=32,
		widget = forms.TextInput(attrs={'class':'form-control','type' : 'text', 'placeholder' : 'Dosen Pengajar'} ))
	ruang_kelas = forms.CharField(label="Ruang Kelas", required=True, max_length=32, 
		widget = forms.TextInput(attrs={'class':'form-control','type' : 'text', 'placeholder' : 'Ruang Kelas'} ))
	sks = forms.IntegerField(label="Jumlah SKS",min_value=1 ,max_value=10,
		widget = forms.NumberInput(attrs={'class':'form-control','type' : 'number', 'placeholder' : 'Jumlah SKS'} ))
	kapasitas = forms.IntegerField(label="Kapasitas Kelas", min_value=1 ,max_value=200,
		widget = forms.NumberInput(attrs={'class':'form-control','type' : 'number', 'placeholder' : 'Kapasitas Kelas'} ))
	semester = forms.ChoiceField(label="Semester", choices=semester_choices,
		widget = forms.Select(attrs={'class':'form-control','type' : 'select'} ))

story4/views.py
from django.shortcuts import render, redirect
from .models import Matkul
from .forms import MatkulForm

# Create your views here.
def isiform(request):
	if (request.method == "POST") :
		form = MatkulForm(request.POST)
		if (form.is_valid):
			form.save()
			return redirect("story4:schedule")
	form = MatkulForm()
	response = {'form' : form}
	return render(request, 'isiform.html', response)


def schedule(request):
	matkuls = Matkul.objects.all()
	response = {}
	response['matkuls'] = matkuls
	return render(request, 'hasilform.html', response)


def detail(request, id):
	matkul = Matkul.objects.get(id=id)
	response = {'matkul' : matkul}
	return render(request, 'detail-matkul.html', response)

def hapus(request, id):
	matkul = Matkul.objects.get(id=id)
	try:
		matkul.delete()
	except:
		pass
	return redirect("story4:schedule")

story4/templates/detail-matkul.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'story4.css' %}">
<title>Detail Matkul {{ matkul.nama_matkul }}</title>
</head>

<body id="formpage">
{% include 'navbar.html' %}
<div class = "container pagelist">
	<a href="{% url 'story4:schedule' %}">
    <button type="button" class="btn addbtn btn-md">Kembali</button>
    </a>
    <h2>{{ matkul.nama_matkul }}</h2>
    <div class="row justify-content-center"><hr class="line-r"></div>
  	<br>
    <div class="row justify-content-center">
    <h5 class="desc">{{ matkul.deskripsi }}</h5>
	</div>
    <br><br>
    <table class="table table-detail"><tbody>
    	<tr><td><h5>Nama Dosen</h5></td><td><h5>: {{ matkul.dosen_pengajar }}</h5></td></tr>
		<tr><td><h5>Nama Kelas</h5></td><td><h5>: {{ matkul.ruang_kelas }}</h5></td></tr>
		<tr><td><h5>Kapasitas</h5></td><td><h5>: {{ matkul.kapasitas }}</h5></td></tr>
		<tr><td><h5>Jumlah SKS</h5></td><td><h5>: {{ matkul.sks }}</h5></td></tr>
		<tr><td><h5>Tahun Ajaran</h5></td><td><h5>: {{ matkul.semester }}</h5></td></tr></tbody>
	</table>

    <br>
    <span class="text-right">
    <!-- Button trigger modal -->
    <button type="button" class="btn addbtn btn-md" data-toggle="modal" data-target="#exampleModal">Hapus</button>
    </span>

    <!-- Modal -->
	<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h4 class="modal-title" id="exampleModalLabel"><b>{{ matkul.nama_matkul }}</b></h4>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <div class="modal-body">
	        Apakah anda yakin ingin menghapus Mata Kuliah ini ?
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
	        <a href="{% url 'story4:idhapus' matkul.id %}"><button type="button" class="btn addbtn btn-md">Ya</button></a>
	      </div>
	    </div>
	  </div>
	</div>

    </div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

{% endblock content %}

story4/templates/hasilform.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'story4.css' %}">
<title>Mata Kuliah</title>
</head>

<body id="formpage">
{% include 'navbar.html' %}
    <div class = "container pagelist">

     <h1>MATA KULIAH</h1>
     <div class="row justify-content-center"><hr class="line-r"></div>
     <br>
    {% if matkuls %}

    <table class="table mytable table-striped">
    <thead class="thead ">
        <tr>
            <th scope="col">No</th>
            <th scope="col">Mata Kuliah</th>
            <th scope="col">Nama Dosen</th>
            <th scope="col">Kelas</th>
            <th scope="col">Semester</th>
        </tr>
    </thead>
    <tbody class="tbody">
    {% for matkul in matkuls %}  
        <tr>        
            <td>{{ forloop.counter }}</td>
            <td>{{ matkul }}</td>
            <td>{{ matkul.dosen_pengajar }}</td>
            <td><a href="{% url 'story4:iddetail' matkul.id %}">{{ matkul.ruang_kelas }}</a></td>
            <td>{{ matkul.semester }}</td>
        </tr>    
    {% endfor %}
    </tbody>
    </table>
    


    {% else %}
    <h1 style="color:red;">Mata Kuliah tidak ditemukan !</h1>
    {% endif %}

    <br><br><br>
    <a href="{% url 'story4:idisiform' %}">
    <button type="button" class="btn addbtn btn-lg btn-block">Tambahkan Mata Kuliah Baru</button>
    </a>
    </div>

{% endblock content %}

story4/templates/isiform.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'story4.css' %}">
<title>Tambahkan Mata Kuliah</title>
</head>

<body id="formpage">
{% include 'navbar.html' %}

<div class = "container pageadd">
    <!-- back button -->
    <a href="{% url 'story4:schedule' %}">
    <button type="button" class="btn addbtn btn-md">Kembali</button>
    <br><br>
    </a>
	<h2>FORM PENAMBAHAN MATA KULIAH BARU</h2>
	<br>
	<form action="" method="POST">
    	{% csrf_token %}
        
    	{% for item in form %}
    		{{ item.label }}{{ item }}<br>
    	{% endfor %}
    	<br>
        <button type="submit" class="btn addbtn btn-lg btn-block">Submit Form</button>
	</form>
</div>


{% endblock content %}