paypewe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story1/', include('story1.urls')),
    path('', include('story3.urls')),
    path('schedule/', include('story4.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

handler404 = 'story3.views.error_404'

story1/urls.py
from django.contrib import admin
from django.urls import path, include
from story1 import views

app_name = "story1"

urlpatterns = [
    path('', views.index, name='idindex'),
]

story9/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from story9 import views

app_name = "story9"

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.loginsite, name='loginsite'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('logout/', views.logoutsite, name='logoutsite'),
    path('signup/', views.signupsite, name='signupsite'),
]

story9/models.py
from django.db import models
from django.contrib.auth.models import User;

# Create your models here.
class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	name = models.CharField(max_length = 64, default="", blank=True)
	image = models.CharField(max_length = 500, default = "https://bit.ly/paypewe_profile_pic")

story9/forms.py
from django import forms

class ProfileForm(forms.Form):
	Name = forms.CharField(label='Full Name', required=True, max_length=64,
		widget = forms.TextInput(attrs={'class':'form-control','type' : 'text', 'placeholder' : 'Pay Pewe'} ))
	Image = forms.CharField(label='Image Url', required=False, max_length=500, 
		widget = forms.TextInput(attrs={'class':'form-control','type' : 'text', 'placeholder' : 'https://bit.ly/paypewe_profile_pic'} ))
	

story9/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseBadRequest
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .forms import ProfileForm
from .models import Profile
from django.contrib import messages


def index(request):
	return redirect('story3:intro')

def loginsite(request):
	response = {}
	if(request.method == "POST"):
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			# print("logging in")
			return redirect('story9:profile', username=user.username)
        
		else:
			try:
				user = User.objects.get(username=username)
				messages.error(request, "Wrong Password ❗")
				# print("forgot password ?")
			except:
				messages.error(request, "User not Found ❗")
				# print("user not found")

	return render(request, "masuk.html")


def profile(request, username):
	response = {}
	response['status'] = False
	user = get_object_or_404(User, username=username)
	response['user'] = user
	profile = get_object_or_404(Profile, user=user)
	response['profile'] = profile


	if(request.method == "POST" ):
		if(request.user.is_authenticated and username == request.user.username):
			form = ProfileForm(request.POST)
			if (form.is_valid()):
				name = form.cleaned_data.get('Name')
				profile.name = name
				image = form.cleaned_data.get("Image")
				profile.image = image
				profile.save()
				messages.success(request, "Profile Updated ✨")

			else:
				messages.error(request, "Invalid Input ❗")

	form = ProfileForm(initial={'Name': profile.name, 'Image': profile.image })
	response['form'] = form
	#user adalah dirinya
	if (request.user.is_authenticated and username == request.user.username):
		response['status'] = True
	
	return render(request, "profile.html", response)


def signupsite(request):
	if (request.method == "POST") :
		form = UserCreationForm(request.POST)
		if (form.is_valid()):
			form.save()
			# print("berhasil")
			username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=username, password=raw_password)
			profile = Profile.objects.create(user = user)
			profile.name = username
			profile.save()
			login(request, user)
			return redirect("story9:index")

		else:
			username = form.cleaned_data.get('username')
			if username is None : 
				messages.error(request, "Username Already Taken ❗")
				# print("username already taken")
			else:
				messages.error(request, "Invalid Input❗")
				# print("Invalid Input")		
				
	form = UserCreationForm()
	response = {'form' : form}
	return render(request, 'daftar.html', response)

def logoutsite(request):
	logout(request)
	return redirect('story9:index')

story9/templates/daftar.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'story9.css' %}">
<title>Sign Up</title>
</head>


<body class="auth-page">
{% include 'navbar.html' %}



<div class = "container authlist justify-content-center">
  {% for message in messages %}
  <div class="alert alert-danger">
    <a class="close" data-dismiss="alert">❌</a>
    {{message}}
  </div>
  {% endfor %}
  <h1 class="mb-5">Register</h1>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
        <h3 class="m-3">{{ field.label_tag }}</h3>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
    {% endfor %}
    <div class="text-center">
      <button type="submit" class="btn loginbtn btn-lg my-5">Sign Up</button>
    </div>
    <p class="my-3 text-center">Already have an account ?
  <a href="{% url 'story9:loginsite' %}">Sign In</a>
  </p>
  </form>

</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

{% endblock %}

story9/templates/masuk.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'story9.css' %}">
<title>Login</title>
</head>


<body class="auth-page">
{% include 'navbar.html' %}

<div class = "container authlist justify-content-center">
	{% for message in messages %}
	  <div class="alert alert-danger">
	    <a class="close" data-dismiss="alert">❌</a>
	    {{message}}
	  </div>
	{% endfor %}
	
	<h1 class="mb-5">User Login</h1>
	<form action="" method="POST">
		{% csrf_token %}
		<h3 class="m-3">Username</h3>
		<div class="form-group text-center">
			<input type="text" name="username" class="form-control"><br/>
		</div>
		<h3 class="m-3">Password</h3>
		<input type="password" name="password" class="form-control"><br/>

		<div class="text-center">
		<button type="submit" class="btn loginbtn btn-lg mt-3 mb-5">Sign In</button>
		</div>
		
	</form>
	<p class="mt-5 text-center">Don't have an account ?
	<a href="{% url 'story9:signupsite' %}">Create One</a></p>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

{% endblock content %}

story9/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'story9.css' %}">
<title>Profile</title>
</head>


<body class="auth-page">
{% include 'navbar.html' %}
<div class = "container pagelist justify-content-center">
	{% for message in messages %}
 		{% if message.tags == 'success' %}
		<div class="alert alert-success">
		    <a class="close" data-dismiss="alert">❎</a>
		   	{{message}}
		</div>
		{% else %}
		<div class="alert alert-danger">
		    <a class="close" data-dismiss="alert">❌</a>
		   	{{message}}
		</div>
		{% endif %}
	{% endfor %}

	<div class="text-center">
	<img class="m-3" src="{{profile.image}}" alt="image" style="object-fit: cover; object-position: 50% 0;border-radius: 50%; border-style: solid; height: 200px; width: 200px;"> 
	</div>
	<h1>{{ profile.name }}'s Profile</h1>
	<h5 class="mb-5 text-muted text-center">@{{ user.username }}</h5>
	<br>
	{% if status %}
	<div class="profform justify-content-center">
		<form action="" method="POST">
			{% csrf_token %}
			<table class="table table-detail">
				{{ form }}
			</table>
			<div class="text-right">
				<button type="submit" class="btn loginbtn btn-lg">Save</button>
			</div>
		</form>
	</div>
	<br>
	<div class="my-5">
	<a href="{% url 'story9:logoutsite' %}">
		<button type="button" class="btn signupbtn btn-lg">Logout</button>
	</a>
	</div>
	{% endif %}
</div>
	
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

{% endblock content %}